#!/bin/sh

function main()
{
  sqpack

  toss

  if [ -f $WORKDIR$/echotoss.log ] ; then rm $WORKDIR$/echotoss.log ; fi
  hpt scan

  if [ -f $WORKDIR$/import.log ] ; then rm $WORKDIR$/import.log ; fi
  hptlink

  purgeDupes

  toss
}

main >> $logdir$/husky.log 2>&1

